---
title: "Running Maps"
output: 
  html_document:
    includes:
      after_body: footer.html
editor_options: 
  chunk_output_type: console
---

<link rel="stylesheet" href="kraustralia/kraustralia.css" type="text/css">

<br/>
<br/>
<br/>

```{r, echo = FALSE, message = FALSE, warning=FALSE, comment = FALSE}
 ## Load libraries
  library(sf)
  library(geosphere)
  library(tidyverse)
  library(basemaps)
  library(maps)
  library(tmap)

 ## Source Custom Functions
  source("~/projects/andykrause.github.io/functions/mapping_functions.R")

 ## Set Paths

  file_path <- '~/documents/_travel/america'
  image_path <- 'x'
```

```{r, echo = FALSE, message = FALSE, warning=FALSE, comment = FALSE}

  ## Load Running Shapefile
  running_sf <- sf::st_read(file.path(file_path, 'running.shp'),
                            quiet=TRUE) %>%
    sf::st_transform(4269) 

  ## Split into trail/road 

  trailruns_sf <- running_sf %>%
    dplyr::filter(!is.na(type)) %>%
    dplyr::filter(type == 'trail') %>%
    dplyr::select(name, type) %>%
    group_by(name, type) %>% 
    summarise(segments = dplyr::n()) %>% 
    st_cast() %>%
    dplyr::select(-segments)

  roadruns_sf <- running_sf %>%
    dplyr::filter(!is.na(type)) %>%
    dplyr::filter(type != 'trail') %>%
    dplyr::select(name, type)

  `Trail Runs` <- trailruns_sf
  `Road Runs` <- roadruns_sf

  trail_col <- 'springgreen3'
  road_col <- 'burlywood4'
  basemap <- leaflet::providers$CartoDB.DarkMatter
  
```

&nbsp;
&nbsp;

## Seattle Area

```{r, echo = FALSE, cache = FALSE, comment = FALSE, warning = FALSE, message = FALSE, fig.width = 6, fig.height = 4}

## Seattle Area

bbox_sea <- st_bbox(trailruns_sf) # current bounding box
bbox_sea[1] <- -122.45
bbox_sea[2] <- 47.4
bbox_sea[3] <- -121.87
bbox_sea[4] <- 47.8

tmap_mode("view")

tm_shape(`Trail Runs`, bbox = bbox_sea) + 
   tm_basemap(basemap) +
   tm_lines(col = trail_col, scale = 1, legend.lwd.show = TRUE) +
   tm_shape(`Road Runs`, bbox = bbox_sea) + 
     tm_lines(col = road_col, scale = 1, legend.lwd.show = FALSE)
  


```

&nbsp;
&nbsp;

## San Juan Islands 

```{r, echo = FALSE, cache = FALSE, comment = FALSE, warning = FALSE, message = FALSE, fig.width = 6, fig.height = 4}

## San Juans
bbox_sji <- st_bbox(trailruns_sf) # current bounding box
bbox_sji[1] <- -123.17
bbox_sji[2] <- 48.39
bbox_sji[3] <- -122.42
bbox_sji[4] <- 48.74

tmap_mode("view")

tm_shape(`Trail Runs`, bbox = bbox_sji) + 
  tm_basemap(basemap) +
  tm_lines(col = trail_col, scale = 1, legend.lwd.show = TRUE) +
  tm_shape(`Road Runs`, bbox = bbox_sji) + 
  tm_lines(col = road_col, scale = 1, legend.lwd.show = FALSE)

```

## Methow Valley

```{r, echo = FALSE, cache = FALSE, comment = FALSE, warning = FALSE, message = FALSE, fig.width = 6, fig.height = 4}

bbox_maz <- st_bbox(trailruns_sf)  
bbox_maz[1] <- -120.53
bbox_maz[2] <- 48.50
bbox_maz[3] <- -120.28
bbox_maz[4] <- 48.66

tmap_mode("view")

tm_shape(`Trail Runs`, bbox = bbox_maz) + 
  tm_basemap(basemap) +
  tm_lines(col = trail_col, scale = 1, legend.lwd.show = TRUE) +
  tm_shape(`Road Runs`) + 
  tm_lines(col = road_col, scale = 1, legend.lwd.show = FALSE)

```

## Hawaii

```{r, echo = FALSE, cache = FALSE, comment = FALSE, warning = FALSE, message = FALSE, fig.width = 6, fig.height = 4}

bbox_haw <- st_bbox(trailruns_sf)  
bbox_haw[1] <- -156.10
bbox_haw[2] <- 19.70
bbox_haw[3] <- -155.61
bbox_haw[4] <- 20.06

tmap_mode("view")

tm_shape(`Trail Runs`, bbox = bbox_haw) + 
  tm_basemap(basemap) +
  tm_lines(col = trail_col, scale = 1, legend.lwd.show = TRUE) +
  tm_shape(`Road Runs`) + 
  tm_lines(col = road_col, scale = 1, legend.lwd.show = FALSE)

```
 