---
title: "Trail Races"
output: 
  html_document:
    includes:
      after_body: footer.html
editor_options: 
  chunk_output_type: console
---

<link rel="stylesheet" href="kraustralia/kraustralia.css" type="text/css">

<br/>
<br/>
<br/>

```{r, echo = FALSE, message = FALSE, warning=FALSE, comment = FALSE}
 ## Load libraries
  library(sf)
  library(geosphere)
  library(tidyverse)
  library(basemaps)
  library(maps)
  library(tmap)

 ## Source Custom Functions
  source(file.path(getwd(), "functions/mapping_functions.R"))

 ## Set Paths

  file_path <- '~/dropbox/andy/_travel/america'
  image_path <- 'x'
  
```

```{r, echo = FALSE, message = FALSE, warning=FALSE, comment = FALSE}

  ## Load Running Shapefile
  cutthroat_sf <- sf::st_read(file.path(file_path, '_events',
                                        'cutthroat_classic.shp'),
                            quiet=TRUE) %>%
    sf::st_transform(4269) 

  basemap <- leaflet::providers$CartoDB.DarkMatter
  
  elev_dem <- raster::raster("~/dropbox/andy/data/base/elevation/washington_pass.dem")
  https://gis.ess.washington.edu/data/raster/tenmeter/byquad/concrete/index.html
  xx <- "https://gis.ess.washington.edu/data/raster/tenmeter/byquad/concrete/q436.zip"
  temp <- tempfile()
  download.file(xx,temp)
  unzip(zipfile = temp, exdir = "~/downloads/")


  #  elmat = rayshader::raster_to_matrix(elev_dem)
  # elmat %>%
  #    rayshader::sphere_shade(texture = "desert") %>%
  #    rayshader::plot_map()
  # 
  # elmat %>%
  #   sphere_shade(texture = "desert") %>%
  #    add_water(detect_water(elmat), color = "desert") %>%
  #    add_shadow(ray_shade(elmat, zscale = 3), 0.5) %>%
  #    add_shadow(ambient_shade(elmat), 0) %>%
  #    plot_3d(elmat, zscale = 10, fov = 0, theta = 135, zoom = 0.75, phi = 45, windowsize = c(1000, 800))
  # 
  
```

&nbsp;
&nbsp;

## Cutthroat Classic

[Race Website](https://methowtrails.org/events/cutthroat-classic)
&nbsp;
&nbsp;

[Results](https://results.raceroster.com/v2/en-US/results/aruguf2ankx7bx75/results)
&nbsp;
&nbsp;

Time: 1:34.18 -- (17th)
&nbsp;
&nbsp;

Distance: 10.5 Miles
&nbsp;
&nbsp;

Elevation Gain to Pass: 1,965
&nbsp;
&nbsp;

```{r, echo = FALSE, cache = FALSE, comment = FALSE, warning = FALSE, message = FALSE, fig.width = 6, fig.height = 4}

## Seattle Area

bbox_cc <- st_bbox(cutthroat_sf) # current bounding box
bbox_cc[1] <- -120.75
bbox_cc[2] <- 48.5
bbox_cc[3] <- -120.645
bbox_cc[4] <- 48.6

tmap_mode("view")

tm_shape(cutthroat_sf, bbox = bbox_cc) + 
   tm_basemap(basemap) +
   tm_lines(col = 'red') 
  
```

&nbsp;
&nbsp;

## Lord Hill

## Orcas Half (Destination)

## Bigfoot 20

 https://www.rayshader.com/
 
 
 loadzip = tempfile() 
download.file("https://tylermw.com/data/dem_01.tif.zip", loadzip)
localtif = raster::raster(unzip(loadzip, "dem_01.tif"))
unlink(loadzip)