---
title: "WA State Parks Challenge - Interactive Map"
output: 
  html_document:
    includes:
      after_body: footer.html
editor_options: 
  chunk_output_type: console
---

```{r, echo = FALSE, message = FALSE, warning=FALSE, comment = FALSE}

  ## Set libraries
  library(sf)
  library(tmap)

  # Load Data
  data_df <- readRDS(file.path(getwd(), 'data', 'created', paste0('data.RDS')))
  visited_sf <- readRDS(file.path(getwd(), 'data', 'created', paste0('visited.RDS')))
  points_sf <- readRDS(file.path(getwd(), 'data', 'created', paste0('points.RDS')))
  routes_sf <- readRDS(file.path(getwd(), 'data', 'created', paste0('routes.RDS')))
  drives_sf <- readRDS(file.path(getwd(), 'data', 'created', paste0('drives.RDS')))
  hikes_sf <- readRDS(file.path(getwd(), 'data', 'created', paste0('hikes.RDS')))
  ferries_sf <- readRDS(file.path(getwd(), 'data', 'created', paste0('ferries.RDS')))
  boating_sf <- readRDS(file.path(getwd(), 'data', 'created', paste0('boating.RDS')))
  paddle_sf <- readRDS(file.path(getwd(), 'data', 'created', paste0('paddle.RDS')))
  boundaries_sf <- readRDS(file.path(getwd(), 'data', 'created', paste0('boundaries.RDS')))
  
  Parks <- 
   points_sf %>% 
    dplyr::left_join(., data_df %>% dplyr::select(Abbrv, URL = WebPage), by = 'Abbrv') %>%
    dplyr::mutate(`State Parks` = ifelse(Visited == 1, 
                                         paste0(' Been There: ', nrow(visited_sf)),
                                         paste0(' Not Yet: ', nrow(data_df) - nrow(visited_sf)))) %>%
    dplyr::select(ParkName, URL, `State Parks`)

  `Visited Parks` <- boundaries_sf %>%
    dplyr::left_join(., data_df %>% dplyr::select(Abbrv, URL = WebPage), by = 'Abbrv') %>%
    dplyr::filter(Abbrv %in% visited_sf$Abbrv) %>%
    dplyr::select(-c(Order, Weather))
  
  `Parks To Do` <- boundaries_sf %>%
    dplyr::filter(!Abbrv %in% visited_sf$Abbrv) %>%
    dplyr::left_join(., data_df %>% dplyr::select(Abbrv, URL = WebPage), by = 'Abbrv') %>%
    dplyr::select(-c(Order, Weather))
  

  `Drives` <- drives_sf
  `Ferries` <- ferries_sf
  `Boating` <- boating_sf
  `Hikes` <- hikes_sf
  `Paddled` <- paddle_sf

  
```

&nbsp;
&nbsp;

```{r, echo = FALSE, cache = FALSE, comment = FALSE, warning = FALSE, message = FALSE, fig.width = 10, fig.height = 7}

  tmap_mode("view")
  
  tm_shape(`Visited Parks`) + 
    tm_polygons(col = 'darkgreen', alpha = .48) +
    
  tm_shape(`Parks To Do`) + 
    tm_polygons(col = 'black', alpha = .4) +
  
   tm_shape(Drives, alpha = .8) + 
    tm_lines(col = 'burlywood4', scale = 1, legend.lwd.show = TRUE) + 
    
  tm_shape(Ferries, alpha = .8) + 
    tm_lines(col = 'purple', scale = 2, legend.lwd.show = FALSE) + 
    
  tm_shape(Boating, alpha = .8) + 
    tm_lines(col = 'blue', scale = 2, legend.lwd.show = FALSE) + 
    
  tm_shape(Hikes, alpha = .8) + 
    tm_lines(col = 'brown', scale = 1.5, legend.lwd.show = FALSE) + 
    
  tm_shape(Paddled, alpha = .8) + 
    tm_lines(col = 'goldenrod', scale = 1.5, legend.lwd.show = FALSE) + 
    
  tm_shape(Parks, alpha = .8) +
    tm_dots(col='State Parks', palette = c('forestgreen', 'gray20')) 
    


```